# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table fishes (
  id                            integer generated by default as identity not null,
  name                          varchar(255) not null,
  constraint pk_fishes primary key (id)
);


# --- !Downs

drop table if exists fishes cascade;

